#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ] || [ "$branch" = "main" ] || [ "$branch" = "develop" ]; then
  echo "You can't commit directly on $branch branch"
  exit 1
fi